receivers: 
  hostmetrics:
    root_path: /hostfs
    collection_interval: 1s
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:
  otlp: 
    protocols: 
      grpc:

exporters:
  prometheus: 
    endpoint: "0.0.0.0:8889"

processors : 
  batch:

service:
  pipelines: 
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [prometheus]


      