version : "3.9"

services:
  app1 :
    container_name : test1
    build : .
    ports : 
      - 3000:3000

  app2 :
    container_name : test2
    build : .
    ports : 
      - 3001:3000

  app3 :
    container_name : test3
    build : .
    ports : 
      - 3002:3000

